import React, { useEffect, useState } from 'react';
import { apiService } from '../services/api';
import { Location, EnvironmentalInsight } from '../types';
import { Sparkles, Bot } from 'lucide-react';

const FALLBACK_INSIGHTS: EnvironmentalInsight[] = [
  {
    id: '1',
    location_id: 'l1',
    insight_type: 'daily_report',
    title: 'Daily Air Quality Assessment & Advisory',
    content: 'Elevated PM2.5 levels (mean 83.4 µg/m³) detected across southern urban corridors due to stagnant meteorological conditions and morning commuter emissions. Sensitive groups including children, elderly citizens, and individuals with preexisting respiratory conditions are strongly advised to limit prolonged outdoor exertion during peak morning hours.',
    severity: 'WARNING',
    generated_by: 'GROQ_AI',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    location_id: 'l2',
    insight_type: 'health_advisory',
    title: 'Particulate Matter Threshold Exceeded',
    content: 'PM10 concentrations peaked at 162 µg/m³ near industrial transition zones. Local health authorities recommend activating ventilation filtration systems in indoor commercial spaces and enforcing heavy vehicle speed limits along primary arterial routes.',
    severity: 'MODERATE',
    generated_by: 'GROQ_AI',
    created_at: new Date().toISOString(),
  },
];

export const AIInsightsPage: React.FC = () => {
  const [locations, setLocations] = useState<Location[]>([]);
  const [selectedLoc, setSelectedLoc] = useState<string>('');
  const [insights, setInsights] = useState<EnvironmentalInsight[]>(FALLBACK_INSIGHTS);
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    apiService.getLocations().then((locs) => {
      if (locs && locs.length > 0) {
        setLocations(locs);
        setSelectedLoc(locs[0].id);
      }
    }).catch(console.warn);

    apiService.getInsights().then((data) => {
      if (data && data.length > 0) setInsights(data);
    }).catch(console.warn);
  }, []);

  const handleGenerate = async (type: string) => {
    if (!selectedLoc) return;
    setIsGenerating(true);
    try {
      await apiService.generateInsight(selectedLoc, type, true);
      const updated = await apiService.getInsights();
      if (updated && updated.length > 0) setInsights(updated);
    } catch (e) {
      console.warn('Generate error:', e);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-black text-slate-100 uppercase flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-emerald-400" />
            Groq AI Environmental Intelligence
          </h2>
          <p className="text-xs text-slate-400">Contextual interpretations and daily reports powered by llama-3.3-70b-versatile</p>
        </div>

        <div className="flex gap-2">
          <select
            value={selectedLoc}
            onChange={(e) => setSelectedLoc(e.target.value)}
            className="select text-sm w-48"
          >
            {locations.map((l) => (
              <option key={l.id} value={l.id}>
                {l.name} ({l.city})
              </option>
            ))}
          </select>

          <button
            onClick={() => handleGenerate('daily_report')}
            disabled={isGenerating}
            className="btn btn-primary text-xs flex items-center gap-1.5"
          >
            <Bot className="w-4 h-4" />
            {isGenerating ? 'Generating Report...' : 'Generate Daily Report'}
          </button>
        </div>
      </div>

      <div className="space-y-4">
        {insights.map((insight) => (
          <div key={insight.id} className="card space-y-3 border-emerald-500/20">
            <div className="flex justify-between items-start">
              <div>
                <span className="badge badge-online text-[10px] mb-1 inline-block">{insight.insight_type}</span>
                <h3 className="text-lg font-bold text-slate-100">{insight.title}</h3>
              </div>
              <span className={`severity-${(insight.severity || 'INFO').toLowerCase()}`}>
                {insight.severity || 'INFO'}
              </span>
            </div>

            <p className="text-sm text-slate-300 leading-relaxed whitespace-pre-line">
              {insight.content}
            </p>

            <div className="text-[10px] text-slate-500 flex justify-between items-center border-t border-slate-800 pt-2">
              <span>Generated by: {insight.generated_by} (llama-3.3-70b-versatile)</span>
              <span>{new Date(insight.created_at).toLocaleString()}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
