import React, { useEffect, useState } from 'react';
import { apiService } from '../services/api';
import { Location, EnvironmentalInsight } from '../types';
import { Sparkles, Bot, RefreshCw } from 'lucide-react';

export const AIInsightsPage: React.FC = () => {
  const [locations, setLocations] = useState<Location[]>([]);
  const [selectedLoc, setSelectedLoc] = useState<string>('');
  const [insights, setInsights] = useState<EnvironmentalInsight[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    apiService.getLocations().then((locs) => {
      setLocations(locs);
      if (locs.length > 0) setSelectedLoc(locs[0].id);
    });
    apiService.getInsights().then(setInsights);
  }, []);

  const handleGenerate = async (type: string) => {
    if (!selectedLoc) return;
    setIsGenerating(true);
    try {
      await apiService.generateInsight(selectedLoc, type, true);
      const updated = await apiService.getInsights();
      setInsights(updated);
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-black text-slate-100 uppercase flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-emerald-400" />
            Groq AI Environmental Intelligence
          </h2>
          <p className="text-xs text-slate-400">Contextual interpretations and daily reports powered by llama-3.3-70b-versatile</p>
        </div>

        <div className="flex gap-2">
          <select
            value={selectedLoc}
            onChange={(e) => setSelectedLoc(e.target.value)}
            className="select text-sm w-48"
          >
            {locations.map((l) => (
              <option key={l.id} value={l.id}>
                {l.name} ({l.city})
              </option>
            ))}
          </select>

          <button
            onClick={() => handleGenerate('daily_report')}
            disabled={isGenerating}
            className="btn btn-primary text-xs flex items-center gap-1.5"
          >
            <Bot className="w-4 h-4" />
            {isGenerating ? 'Generating Report...' : 'Generate Daily Report'}
          </button>
        </div>
      </div>

      <div className="space-y-4">
        {insights.map((insight) => (
          <div key={insight.id} className="card space-y-3 border-emerald-500/20">
            <div className="flex justify-between items-start">
              <div>
                <span className="badge badge-online text-[10px] mb-1 inline-block">{insight.insight_type}</span>
                <h3 className="text-lg font-bold text-slate-100">{insight.title}</h3>
              </div>
              <span className={`severity-${(insight.severity || 'INFO').toLowerCase()}`}>
                {insight.severity || 'INFO'}
              </span>
            </div>

            <p className="text-sm text-slate-300 leading-relaxed whitespace-pre-line">
              {insight.content}
            </p>

            <div className="text-[10px] text-slate-500 flex justify-between items-center border-t border-slate-800 pt-2">
              <span>Generated by: {insight.generated_by} (llama-3.3-70b-versatile)</span>
              <span>{new Date(insight.created_at).toLocaleString()}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
